### ISSUE TITLE
What is contained in the cwi_utils folder?

### ISSUE THREAD

**Issue by kunjmehta** [nathanshartmann/NILC-at-CWI-2018#3]
Hi Nathan, I am trying to understand your code as a starter for my academic project on text simplification. I have understood the flow of your code but cannot find the `cwi_utils` folder that contains a neural model and the `lm` files. I would hugely appreciate if you could tell me what these files are for and how to obtain them? It would be best if you could upload them.

Thanks!

**Comment by nathanshartmann** [comment]
Please, take a look in the following url:
https://www.dropbox.com/sh/5zrex1otq3cfcy8/AAA7_Vnz_J2pGAbHtD6t-_4va?dl=0

I hope it helps you.
